spring.application.name=expresofast-backend
server.port=8080

# Base de datos del Laboratorio 9
spring.datasource.url=jdbc:sqlserver://163.178.173.130:1433;databaseName=ExpresoFastC5L811_II2026;encrypt=true;trustServerCertificate=true
spring.datasource.username=Lenguajes
spring.datasource.password=lenguajesparaiso2025
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=update
=======
spring.jpa.hibernate.ddl-auto=none
>>>>>>> 1c90a2d51792e18d6e339edf0ebc941348ec1ce9
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
